version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - NODE_ENV=development
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_database
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
