version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: nathanlcr
      POSTGRES_PASSWORD: nathanlcr
      POSTGRES_DB: celebratenow
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  celebrate-now-api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celebrate-now-api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    restart: always

volumes:
  postgres-data: